# Gruvbox theme for Alacritty

[colors.primary]
background = "#282828"
foreground = "#ebdbb2"

[colors.normal]
black = "#282828"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#a89984"
yellow = "#d79921"

[colors.bright]
black = "#928374"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#ebdbb2"
yellow = "#fabd2f"

[colors.cursor]
text = "#d79921"
cursor = "#282828"

[colors.vi_mode_cursor]
text="CellBackground"
cursor="CellBackground"

[colors.selection]
background="#504945"
text="CellBackground"

[colors.search.matches]
background="#fabd2f"
foreground="#504945"

[colors.search.focused_match]
background="#fe8019"
foreground="#504945"

[colors.footer_bar]
background="#282828"
foreground="#ebdbb2"

[colors.hints.start]
background="#282828"
foreground="#d79921"

[colors.hints.end]
background="#d79921"
foreground="#282828"
